### ISSUE TITLE
As a user I need to to see a Roadmap on the storefront so I know what is planned 

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#105]
Prioritized from May 2022 gathering

- [ ] Where should our roadmap live? Can live directly in zeroheight, or can embed and image or file from some place else. 
- [ ] What should be the contents? High level? 
- [ ] Should have a schedule for updating. How often, where to share updates. 

Example: 
https://designsystem.digital.gov/about/product-roadmap/

**Comment by vnys** [comment]
Can we use the [roadmap from Github](https://github.com/equinor/design-system/projects/2) directly?

**Comment by akvam** [comment]
Add a roadmap in Zerohight based on what we decided in the Mai gathering. 
Annonce it on Slack.

**Comment by martalalik** [comment]
1. No need to have a GitHub profile to look into `roadmap`.
2. I came up to other solution that might be useful to have it in Zeroheight (although GitHub can be embedded in Zerohight) or in `Storybook`, for showing status of the components: 

- [altinn DS](https://altinn.github.io/designsystem-styleguide/) 
- [nav ED](https://aksel.nav.no/designsystem/side/oversikt-komponenter)

**Comment by martalalik** [comment]
Standup 19.08
Taking in consideration, informing EDS user about component and work status; during standup we came to conclusion to use Slack instead creating overview in Storybook.
This solution seems easer to maintain.

**Comment by BirteThornquist** [comment]
We need to investigate if this is something that can be automated. How can we best present the roadmap? The real need is how we can tell our users what we plan to do in the future.
