### ISSUE TITLE
Create Button component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#147]
**Description**

Buttons allow users to take action with a single click or tap.

**Documentation**

- [The storefront](https://eds.equinor.com/components/button/)
- [Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=1%3A4)
- [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#button)

**General guidelines**

See [COMPONENT_GUIDELINES.md](https://github.com/equinor/design-system/blob/develop/COMPONENT_GUIDELINES.md) for general guidelines like browser support and common implementation details

**Sub tasks**

- [ ] Write tests
- [ ] Create set of tokens (from base tokens)
- [ ] Update to latest revision of component architecture (#225 )
- [ ] Add example using button as "upload button" in Storybook (#287)
- [x] Create set of tokens (from Figma component tokens)
- [x] Create react component

**Variants**

- [x] Contained
- [ ] Contained w/icon left/right
- [x] Outlined
- [ ] Outlined w/icon left/right
- [x] Ghost
- [ ] Ghost w/icon left/right
- [x] Ghost icon only (#218)
