### ISSUE TITLE
Spike - Plan what to have in EDS Power Apps template

### ISSUE THREAD

**Issue by BeckyBrekke** [equinor/design-system#2134]

**Comment by Hjaf** [comment]
I suggest creating a template which include a screen with all canvas app native controls and some basic patterns as close to EDS standards as we can get them. This approach requires developers to basically copy the controls from this template app or screen into their app or screen, this is a short-term solution. In the long run, the aim should be in converge with PowerPlatform roadmap and possibly [Fluent UI](https://docs.microsoft.com/en-us/power-apps/teams/use-the-fluent-ui-controls) when/if this becomes the default for all canvas (teams, classic, portals etc). Although it may seem a bit crude, I suspect `ctrl-c` -> `ctrl-v` on controls and patterns, may still be the most intuitive method for most citizen developers.

I'm not 100% certain that establishing a convention using app OnStart is optimal at this point, but if we can build on [Matthew Devaney's examples](https://www.matthewdevaney.com/create-a-power-apps-custom-theme-colors-fonts-icons-controls/), a lot of the hard work has already been done. 

The template can include an adjusted Themes.json so the studio functionality (e.g. adding a button) will add themed controls, how ever, this is somewhat experimental, relying on a lot of assumptions and speculation and is easily broken with power platform updates.

### Priority
**(Suggestion)**

1. Fluent UI templates **once this becomes standard/unified** in power platform.
    > [ react -> fluent UI code components](https://www.c-sharpcorner.com/blogs/code-component-in-power-apps-using-react-and-fluent-ui)
2. Simple template for copy&pasting controls
3. Controls with values from theming variable object set by app OnStart property.
    > including object for all EDS icons that can be used in the picture control e.g. `gblEDSIcons.manual_valve` and `gblEDSIcons.platform`
4. Themes.json defaults based controls created (step 2)

### TODO
- [ ] Create template containing all (standard) controls EDS Light/default theme.
- [ ] Create template containing all (standard) controls EDS Dark theme
  > Need some help from @vnys @BeckyBrekke @BirteThornquist  @benteljones and anyone else familiar with PowerApps and design/ux for some of the more advanced controls, like tables, forms.
- [ ] Create some common patterns (layout)
- [ ] Create templates for large, medium and small
- [ ] Create app/function that create a new app from template in the specified environment.
  > Alternative to having the user download and import the file manually
- [ ] Documentation either as standalone or built into the template file itself.

The first templates we publish should be considered "preview", limitations should be highlighted **especially** in terms of accessibility. I also think that giving a "private preview" to the [DigiTeam](https://statoilsrm.sharepoint.com/sites/OTEDigiTEAM) (private group with ~20 members) early on can provide useful feedback from start.

**Comment by vnys** [comment]
Custom controls is another option here. Then at least the controls can be inserted instead of being copied, and we can have more variants of each control – button for example. Can we set up a meeting on Wednesday and discuss?

**Comment by Hjaf** [comment]
Closing this issue as they are covered by other issues mentioned in https://github.com/equinor/design-system/issues/2134#issuecomment-1106363504 

[Internal preview released for everyone to view](https://apps.equinor.com/edspowerapps) (apps.equinor.com/edspowerapps), an unmanaged solution is available for download on request by citizen developers.

Feature request and feedback is facilitated via [form ](https://apps.equinor.com/edspafeedback)(apps.equinor.com/edspafeedback)
