### ISSUE TITLE
Update Button component

### ISSUE THREAD

**Issue by mimarz** [equinor/design-system#298]
**Description**

Update missing states or variants for the `Button` component

**Documentation**

- [The storefront](https://eds.equinor.com/components/button/)
- [Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=1%3A4)
- [WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#button)

**Sub tasks**

- [x] Write tests
- [x] Create set of tokens (from base tokens)
- [ ] Update to latest revision of component architecture (#225 )
- [x] Add example using button as "upload button" in Storybook (#287)
- [x] Fix ghost icon button size to `24px`
- [x] Button as a/link

**Variants**

- [x] Contained
- [x] Contained w/icon left/right
- [x] Outlined
- [x] Outlined w/icon left/right
- [x] Ghost
- [x] Ghost w/icon left/right
- [x] Ghost icon only (#218)
