### ISSUE TITLE
Video documentation: "how to" for components users

### ISSUE THREAD

**Issue by marinalinn** [equinor/design-system#3502]
Prepare material, scripts and examples for video documentation for:

- How to choose space between Selectables.
- How to choose space between Containers.
- How to apply Density

**Scope:**

- Split the videos as much as we can so then is easier for the users to search specific information.
- Use simple examples on the video.
- Increase the examples complexity gradually between chapters.
- Try to communicate the material on short format videos.

**Tasks:**

- [x] Request an Adobe license
- [x] Download Adobe Rush
- [x] Align about the settings to use (resolution, files, examples, etc).
- [x] Align about the typography component usage for the video
- [x] Align opening and closing scripts for the video
- [x] Build the script of the videos
- [x] Record the videos
- [x] Edit the videos: add image at the beginning and end, and the Equinor sound.
- [x] Check the references that will be mentioned on the video
- [x] Upload videos on Degreed
