### ISSUE TITLE
As a developer I need to validate that the EDS components are accessible to disabled users

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#586]
We strive to make the components accessible in both design and code by using helper tools in Figma and Storybook and following [WAI-ARIA best practices](https://www.w3.org/TR/wai-aria-practices-1.1/) – but to be really sure we need some level of user testing. We also have to find out which screen readers are most commonly in use in the company, both to make it easier for ourselves to test our own components – but also to give us some criteria for evaluating third party components. 

**TODO**
- [ ] Create example applications using EDS components
- [ ] Create an a11y test group
  - Can we use Yammer to ask for volunteers?
- [ ] Contact [Norges Blindeforbund](https://www.blindeforbundet.no/) for advice

We should also use tools like [Axe](https://axe.deque.com/) for manual testing.

What else? Add suggestions in comments.

**Comment by akvam** [comment]
It is also an alternative to test a "Figma App".

**Comment by akvam** [comment]
This is a general goal for EDS, but this US is to big be a concreate work. Close this issue, since "ally" has high focus in the team.
