### ISSUE TITLE
As a developer I want to contribute to the EDS for the Hacktober Festivus 🎃

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#602]
- [x] [Register the project](https://github.com/equinor/hacktoberfestivus/pull/6/commits/2d9cbc3610c0fa36b14d24e485904968fded056b) as an arena for Hacktoberfestivus activities.
- [x] Decide on which form the desired contribution should be.
- [x] Create/label issues with "good first issue" suitable for the Hacktoberfestivus
- [x] Brush up README, CONTRIBUTING, “how to run” etc.

**Comment by vnys** [comment]
**TODO**
- [ ] Add how to run to README
- [ ] Add Contributing.md

**Issues**
- Bugfixing
