### ISSUE TITLE
Some epic

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#90]
- [x] Some sub task
- [x] Some sub task
- [ ] Some sub task
- [ ] Some sub task
